# curiosidades.py
tech_facts = [
    "El primer dominio registrado fue symbolics.com el 15 de marzo de 1985.",
    "Hay más potencia de cálculo en tu móvil que en la nave Apolo 11.",
    "El código original de la WWW fue escrito por Tim Berners-Lee en una NeXT.",
    "Nintendo fue fundada en 1889 haciendo cartas Hanafuda.",
    "El email es anterior a la World Wide Web.",
    "Google se llamaba originalmente 'BackRub'.",
    "La contraseña más común en 2024 sigue siendo '123456'.",
    "El primer ratón de ordenador estaba hecho de madera.",
    "Cada minuto se suben más de 500 horas de video a YouTube.",
    "El primer disco duro de 1GB pesaba más de 250 kg (año 1980).",
    "El logotipo de Firefox no es un zorro, es un panda rojo.",
    "Amazon originalmente solo vendía libros y se llamaba Cadabra.",
    "El primer virus informático se llamó Creeper y apareció en 1971.",
    "La 'Nube' no es vapor, son servidores submarinos y granjas de datos.",
    "Facebook es azul porque Mark Zuckerberg es daltónico al rojo-verde.",
    "El primer SMS decía 'Merry Christmas' y se envió en 1992.",
    "La cámara más grande del mundo tiene 3200 megapíxeles.",
    "Solo el 8% del dinero del mundo existe en efectivo físico.",
    "La primera webcam se inventó para vigilar una cafetera en Cambridge.",
    "Bill Gates diseñó su casa usando un Mac.",
    "Los captchas sirven para entrenar a la IA de Google a leer libros.",
    "El término 'Bug' viene de una polilla real atrapada en un relé en 1947.",
    "Android fue creado originalmente para cámaras digitales, no móviles.",
    "YouTube fue creado como una página de citas por video.",
    "Nokia vendía papel higiénico antes que móviles.",
    "El ordenador que controla los misiles nucleares de EEUU usaba disquetes hasta 2019.",
    "La QWERTY se diseñó para que las máquinas de escribir no se atascaran al ir rápido.",
    "Un byte son 8 bits. Un nibble son 4 bits.",
    "El GPS es gratuito para el mundo, pero le cuesta a EEUU 2 millones al día.",
    "SpaceX usa una versión modificada de Linux en sus cohetes Falcon 9."
]
